# Generated by Django 5.2.3 on 2025-06-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_approved_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='venue',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CU', 'Customer'), ('AD', 'Admin'), ('EO', 'Event Owner')], default='CU', max_length=2),
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
