# Generated by Django 5.2.3 on 2025-07-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_event_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/', verbose_name='Event Image'),
        ),
        migrations.AddField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='event_thumbnails/', verbose_name='Thumbnail Image'),
        ),
    ]
