# Generated by Django 5.2.3 on 2025-06-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CU', 'Customer'), ('VO', 'Venue Owner'), ('AD', 'Admin'), ('EO', 'Event Owner')], default='CU', max_length=2),
        ),
    ]
