# Generated by Django 5.2.3 on 2025-07-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event_image_event_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
